CREATE TABLE books(
                      book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      author VARCHAR(255) NOT NULL,
                      publisher VARCHAR(255) NOT NULL,
                      publication_year INTEGER NOT NULL,
                      edition INTEGER NOT NULL,
                      isbn VARCHAR(20) NOT NULL
);

CREATE TABLE members(
                        member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        phone VARCHAR(255) NOT NULL,
                        outstanding_fine BIGINT NOT NULL DEFAULT 0,
                        status VARCHAR(255) NOT NULL
);

CREATE TABLE book_records(
                             book_record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             book_id BIGINT NOT NULL,
                             status VARCHAR(255) NOT NULL,

                             CONSTRAINT fk_book_records_book
                                 FOREIGN KEY (book_id)
                                     REFERENCES books(book_id)
);

CREATE TABLE borrow_records(
                               borrow_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               member_id BIGINT NOT NULL,
                               book_record_id BIGINT NOT NULL,

                               borrow_date DATE NOT NULL,
                               due_date DATE NOT NULL,
                               return_date DATE,

                               status VARCHAR(255) NOT NULL,

                               voided_by VARCHAR(255),
                               void_reason VARCHAR(255),
                               voided_at TIMESTAMP,

                               CONSTRAINT fk_borrow_records_member
                                   FOREIGN KEY (member_id)
                                       REFERENCES members(member_id),

                               CONSTRAINT fk_borrow_records_book_record
                                   FOREIGN KEY (book_record_id)
                                       REFERENCES book_records(book_record_id)
);

CREATE TABLE user_accounts(
                              user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              email VARCHAR(255) NOT NULL UNIQUE,
                              password VARCHAR(255) NOT NULL,
                              role VARCHAR(255) NOT NULL,
                              enabled BOOLEAN NOT NULL,

                              member_id BIGINT UNIQUE,

                              CONSTRAINT fk_user_accounts_member
                                  FOREIGN KEY (member_id)
                                      REFERENCES members(member_id)
);